import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY;

export const generateRealKolam = async (base64Image: string): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key not found");
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
    You are an expert visual effects artist specializing in Augmented Reality blending.
    
    The input image consists of a REAL photo of a floor/environment with simple DIGITAL VECTOR OVERLAYS (white patterns, icons) placed on top.
    
    YOUR TASK:
    Generate a photorealistic version of this scene where the digital overlays are replaced by real physical materials.
    
    SPECIFIC INSTRUCTIONS:
    1. **Kolam Patterns (White Lines):** The digital white lines MUST become **traditional Rice Flour Powder (Rangoli)**. 
       - They should look grainy, powdery, and textured. 
       - They must sit *on* the floor surface, reacting to the floor's roughness.
       - They must NOT look like glowing lines, paint, or stickers. They should look like hand-poured powder.
       
    2. **Pongal Pot (Icon):** Replace the icon with a **real Earthenware Clay Pot** cooking Pongal. 
       - It should be overflowing with white frothy milk. 
       - It must cast a realistic shadow on the floor matching the scene's lighting.
       
    3. **Sugarcane (Icon):** Replace with **real purple/green Sugarcane stalks** with natural leaves.
    
    4. **Sun (Icon):** Replace with a pattern made of yellow flower petals or yellow powder.

    5. **Background & Perspective:** 
       - PRESERVE the original floor texture, lighting, and background details EXACTLY. 
       - Do not change the room. 
       - Ensure the new objects follow the perspective of the floor.

    The final output should look like a legitimate photograph of a Thai Pongal celebration, not a digital edit.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [
        {
          text: prompt
        },
        {
          inlineData: {
            mimeType: 'image/png',
            data: base64Image
          }
        }
      ],
      config: {
        temperature: 0.4, // Lower temperature for better adherence to the source image structure
      }
    });

    // Extract the image from the response
    let generatedImageBase64 = null;

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
                generatedImageBase64 = part.inlineData.data;
                break;
            }
        }
    }

    if (!generatedImageBase64) {
        throw new Error("No image generated by the model.");
    }

    return `data:image/png;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};