import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY;

export const generateRealKolam = async (base64Image: string): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key not found");
  }

  const ai = new GoogleGenAI({ apiKey });

  const prompt = `
    You are an expert visual effects artist and traditional Kolam artist.
    
    The input image is a photo of a floor with digital vector overlays.
    
    YOUR TASK:
    Transform the digital overlays into a single, magnificent, CIRCULAR KOLAM (Rangoli) design made of real rice flour and flower petals on the floor.
    
    CRITICAL DESIGN RULES:
    1. **Unified Circle:** Regardless of how scattered the input items are, organize the generated output into ONE SINGLE COHESIVE CIRCULAR DESIGN (Mandala style).
    2. **Material:** Use white rice flour powder for the intricate lines and yellow/orange flower petals for accents. The texture must be powdery and realistic.
    3. **Patterns:** Transform the simple lines/dots into a complex, traditional circular geometric pattern.
    
    REALISM:
    - The design must look like it was hand-drawn on the specific floor in the image.
    - Preserve the floor texture, lighting, and perspective relative to the camera.
    - Add realistic shadows for the pot and sugarcane.
    
    Output a photorealistic image of this circular Kolam celebration setup.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [
        {
          text: prompt
        },
        {
          inlineData: {
            mimeType: 'image/png',
            data: base64Image
          }
        }
      ],
      config: {
        temperature: 0.4, // Lower temperature for better adherence to the source image structure
      }
    });

    // Extract the image from the response
    let generatedImageBase64 = null;

    if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData && part.inlineData.data) {
                generatedImageBase64 = part.inlineData.data;
                break;
            }
        }
    }

    if (!generatedImageBase64) {
        throw new Error("No image generated by the model.");
    }

    return `data:image/png;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
